#!/usr/bin/bash
cd tools

# for the nrf5 17.1 sdk go here https://www.nordicsemi.com/Products/Development-software/nRF5-SDK/Download#infotabs

wget "https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2?revision=05382cca-1721-44e1-ae19-1e7c3dc96118&rev=05382cca172144e1ae191e7c3dc96118&hash=FDE675133A099796BD1507A3FF215AC4" \
  -O "gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2" \
  && tar -xf "gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2"
